import { Link } from "react-router-dom";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div className="mx-auto max-w-6xl px-4 py-10">
      <motion.section
        initial={{ opacity: 0, y: 14 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
        className="relative overflow-hidden rounded-3xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900"
      >
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute -top-24 -left-24 h-72 w-72 rounded-full bg-blue-500/10 blur-3xl" />
          <div className="absolute -bottom-24 -right-24 h-72 w-72 rounded-full bg-purple-500/10 blur-3xl" />
        </div>

        <div className="relative p-8 sm:p-12">
          <div className="inline-flex items-center gap-2 rounded-full border border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-950 px-3 py-1 text-xs text-gray-700 dark:text-gray-200">
            <span className="h-2 w-2 rounded-full bg-green-500" />
            AI-Powered Store Demo
          </div>

          <h1 className="mt-4 text-3xl sm:text-4xl font-bold tracking-tight">
            Welcome to <span className="text-blue-600 dark:text-blue-400">E-Commer</span>
          </h1>

          <p className="mt-3 max-w-2xl text-gray-600 dark:text-gray-300 leading-relaxed">
            In this project, we use AI support to help create product information.
            Product <span className="font-semibold">descriptions</span> can be generated by AI,
            and product <span className="font-semibold">images</span> can also be AI-generated (backend integration can be added next).
          </p>

          <div className="mt-6 flex flex-wrap items-center gap-3">
            <Link
              to="/products"
              className="inline-flex items-center justify-center rounded-md bg-black text-white px-5 py-2.5 text-sm font-medium hover:bg-gray-900 dark:bg-white dark:text-black dark:hover:bg-gray-200 transition"
            >
              Go to Products →
            </Link>

            <div className="text-sm text-gray-500 dark:text-gray-400">
              Use <span className="font-semibold">Add Item</span> in Navbar to add a new product.
            </div>
          </div>
        </div>
      </motion.section>
    </div>
  );
}
